name: Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        cmake -E make_directory build
        cd build
        cmake -A "x64" ..
    - name: Compile
      working-directory: build
      run: cmake --build . -j2 
    - name: Test
      working-directory: build
      run: |
         dir
         Debug\test.exe
